### PR TITLE
Eslint prettier cspell

### PR DESCRIPTION
**Pull request by J3m5**
This pull request adds eslint, prettier and cspell as dependencies and add scripts for using them.
They have been used to format, enforce eslint rules and fix spelling errors.
Some code and types refactoring have been made too.
The `isPending` getter on the BaseModel has been implemented as it was missing but its type was present on the Model interface.

### CODE REVIEW

**Comment by marshallswain** [comment]
This is an impressive amount of cleanup you've applied.  Leave a comment when you feel it's ready.  I've reviewed everything up to now.  I'll review any new work after you give the word.

Thanks for doing this.  It REALLY cleans things up.  This is also the first that I've seen cspell.

**Comment by J3m5** [comment]
You're welcome!
One thing I'll double check is the use of the [Record type](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) that I introduced.
There is some place where it is more appropriate to use [index signatures](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) instead because naming the key can help in some context.

**Comment by J3m5** [comment]
It's ready!

**Comment by marshallswain** [comment]
Looks great!  Thank you.

**Pull request merged**
