### PR TITLE
fix: update defineStore wrapper options to match pinia's

### LINKED ISSUE #14: The defineStore() wrapper expects state to be an object and not a function like pinia
### Context:
**pinia:** the native `defineStore()` method requires state to be a function which returns an object e.g. `state: () => ({...})`.

**feathers-pinia:** the `defineStore()` method expects an object directly e.g. `state: {...}`.

### Problem:
Developers can easily forget to pass an object causing store state to not be merged correctly.

### Solution:
The feathers-pinia `defineStore()` wrapper should also only expect a function so that the wrapper can pass the options 'as is' to the original `defineStore()`.

### PR DESCRIPTION
**Pull request by miguelrk**
Closes #14

### CODE REVIEW

**Comment by marshallswain** [comment]
We probably need the following before we can merge:

1. Test to make sure we can customize the store
2. Docs showing how to customize.  I can't remember if these already exist.

**Comment by marshallswain** [comment]
Also, thank you!

**Comment by miguelrk** [comment]
I got a basic test passing which tests full interaction with the store (read/write state, read getters, dispatch actions). I'm relatively new to testing, but if you have any other testing ideas feel free to let me know 👍🏼 . I think I updated the docs everywhere (at least where I could find it). Also, I removed the unnecessary @vue/composition-api dependency. Otherwise this is ready to merge I guess.

**Review by miguelrk — COMMENTED** [review]
Sorry for the noise, I mistakenly commited unwanted files but deleted them already. Otherwise looks good.

**Pull request merged**
