### PR TITLE
feat: changes imports from 'vue' to from 'vue-demi' for vue2 support

### PR DESCRIPTION
**Pull request by miguelrk**
This PR simply replaces all `import ... from 'vue'` with `import ... from 'vue-demi'` to allow using `feathers-pinia` with vue2. All tests are passing locally and build is working correctly as well.

NOTE: The project and package.json seemed was already prepared to implement `vue-demi`, it was I believe simply missing to replace the exports as mentioned [here](https://feathersjs.slack.com/archives/C11VCU0Q4/p1630622581023500?thread_ts=1630193822.010300&cid=C11VCU0Q4). 

 Anyways, let me know if there are issues with this, I'm new to lib development/contributions

### CODE REVIEW

**Comment by marshallswain** [comment]
Thanks for the PR @miguelrk!  Could you review it and remove any lines that are only editing whitespace?

**Comment by miguelrk** [comment]
There! All done 👍🏼, sorry for those I didn't notice them at first

**Comment by miguelrk** [comment]
Thanks @marshallswain for the quick merge and publish! 

I'm sorry to tell that after testing consuming v0.16.0 with a vue2 application it did not work. I have however found the issue...

### Context:

With the current build config, rollup outputs the following: 
```javascript
// dist/feathers-pinia.es.js

import { unref, computed, reactive, watch, toRefs, isRef } from "vue";
```

This fails for an app running in a vue2 environment, since in that case, imports should come from `"@vue/composition-api"` and not `"vue"`. What (to my knowledge) should be the desired output is:

```javascript
// dist/feathers-pinia.es.js

import { unref, computed, reactive, watch, toRefs, isRef } from "vue-demi";
```
so that the consuming application resolves to `"@vue/composition-api"` if vue2 detected, or else `"vue"` if vue3 detected by vue-demi.

### Issue:
The issue is in the build configuration specified in vite.config.ts (see also [here](https://github.com/vueuse/vue-demi/issues/69#issuecomment-877331251) and [here](https://github.com/vueuse/vue-demi/issues/108)).

### Solution:

Updating the build configuration to externalize 'vue-demi' and also adding it as a global fixes this, producing the desired output above:
```javascript
// vite.config.ts

 build: {
    lib: {
      entry: path.resolve(__dirname, 'src/index.ts'),
      name: 'feathersPinia',
    },
    sourcemap: true,
    rollupOptions: {
      // make sure to externalize deps that shouldn't be bundled
      // into your library
      external: ['vue-demi', 'vue', 'pinia', 'lodash', 'sift'],
      output: {
        // Provide global variables to use in the UMD build
        // for externalized deps
        globals: {
          'vue-demi': 'VueDemi',
          vue: 'Vue',
          pinia: 'pinia',
          lodash: 'lodash',
          sift: 'sift',
        },
      },
    },
  }
  ```
 
 A new PR with this fix is on the way.
 
 PS: sorry for another patch, it didn't occur to me I could test it locally by simply copy-pasting the /dist output into node_modules/feathers-pinia/dist of my local vue2 application.

**Comment by marshallswain** [comment]
Sounds great!  I figured it would either work or we would find a fix
after somebody found that it wouldn’t work.  Thanks for sticking around
to get it working.

On November 24, 2021, GitHub ***@***.***> wrote:
> Thanks @marshallswain <https://github.com/marshallswain> for the quick
> merge and publish!
>
> I'm sorry to tell that after testing consuming v0.16.0 with a vue2
> application it did not work. I have however found the issue...
>
> Context:With the current build config, rollup outputs the following:
>
> // dist/feathers-pinia.es.js import { unref, computed, reactive,
> watch, toRefs, isRef } from "vue";
> This fails for an app running in a vue2 environment, since in that
> case, imports should come from ***@***.***/composition-api" and not "vue".
> What (to my knowledge) should be the desired output is:
>
> // dist/feathers-pinia.es.js import { unref, computed, reactive,
> watch, toRefs, isRef } from "vue-demi";
> so that the consuming application resolves to ***@***.***/composition-api"
> if vue2 detected, or else "vue" if vue3 detected by vue-demi.
>
> Issue:The issue is in the build configuration specified in
> vite.config.ts (see also here <https://github.com/vueuse/vue-
> demi/issues/69#issuecomment-877331251> and here
> <https://github.com/vueuse/vue-demi/issues/108>).
>
> Solution:Updating the build configuration to externalize 'vue-demi'
> and also adding it as a global fixes this, producing the desired
> output above:
>
> // vite.config.ts build: { lib: { entry: path.resolve(__dirname,
> 'src/index.ts'), name: 'feathersPinia', }, sourcemap: true,
> rollupOptions: { // make sure to externalize deps that shouldn't be
> bundled // into your library external: ['vue-demi', 'vue', 'pinia',
> 'lodash', 'sift'], output: { // Provide global variables to use in the
> UMD build // for externalized deps globals: { 'vue-demi': 'VueDemi',
> vue: 'Vue', pinia: 'pinia', lodash: 'lodash', sift: 'sift', }, }, }, }
> A new PR with this fix is on the way.
>
> PS: sorry for another patch, it didn't occur to me I could test it
> locally by simply copy-pasting the /dist output into
> node_modules/feathers-pinia/dist of my local vue2 application.
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/marshallswain/feathers-pinia/pull/12#issuecomment-
978131255>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAA7OWM7SSLYEKATDVOB44LUNUWG5ANCNFSM5IV3HKTA>.

**Pull request merged**
