### PR TITLE
fix: stores not being registered in devtools

### LINKED ISSUE #16: Stores registered with feathers-pinia not showing-up in the devtools
**TLDR:** Original `defineStore()` called with `options.storeId` instead of `options.id` and pinia requires `options.id` to register store in vue devtools.

### Issue

Stores created with feathers-pinia not showing-up in vue devtools (at least when using vue2).

### Context

From pinia docs: 
> This name, also referred as id, is necessary and is used by Pinia to connect the store to the devtools.

### Solution

In this case, the only fix should be to rename the expected `options.storeId` to `options.id` to at least have a more transparent/direct mapping to the pinia API.  This change does not break tests and remains backwards compatible.

So basically change the following code:
```diff
  // Create and initialize the Pinia store.
  const storeOptions: any = makeServiceStore({
-   storeId: options.id || `service.${options.servicePath}`,
+   id: options.id || `service.${options.servicePath}`,
    idField: options.idField || idField || 'id',
    clientAlias,
    servicePath,
    clients,
    Model: options.Model,
    state,
    getters,
    actions,
    whitelist,
  })
  function useStore(pinia?: Pinia): any {
    const useStoreDefinition = definePiniaStore(storeOptions)
    ...
  }
```

### PR DESCRIPTION
**Pull request by miguelrk**
I can confirm this fixes the issue of stores not showing-up in devtools.

Closes #16

### CODE REVIEW

**Comment by miguelrk** [comment]
@marshallswain I basically did a find and replace for `storeId` with `id` throughout the codebase (only 3 places in total). Let me know what you think about renaming feathers-pinia's `defineStore` to avoid confusion with the original considering the feathers-pinia currently only accepts one argument (`options` object). 

My personal opinion is to keep the `defineStore` name since aligning both APIs is indeed intended and although maybe not really needed yet, it would allow this in the future. 

Also, feathers-pinia currently sets the default `id` to `service.${servicePath}` if options.id does not exist.

```javascript
id: options.id || `service.${options.servicePath}`,
```

should we maybe change it to simply the servicePath?
```javascript
id: options.id || options.servicePath,
```
This I think would align with pinia's pattern of modular/composable stores and maybe encourage feathers-pinia service stores to align more and more to regular pinia stores (that is what they really are at the end). Not a strong opinion though, we would also need to update the tests.

**Comment by marshallswain** [comment]
My goal has always been to keep the same API as Pinia.  If Pinia has made changes since I last updated this, then we need to change our API to match.  I think your PR is inline with that goal, right?

**Comment by miguelrk** [comment]
I agree, both APIs should align. Thus we should keep related method/props names the same between APIs. 

This PR specifically fixes the issue of stores created with feathers-pinia's `defineStore(options)` not showing up in devtools and the fix was simply replacing `options.storeId` with `options.id`, how pinia now handles this. This takes a step towards aligning both APIs, yes (pinia now uses `id`, that was the root of the devtools problem).

I would say to merge/release this PR and open a separate (larger) one to focus on aligning both APIs, specifically the `defineStore()` method, which is currently behind at least in the 3 signatures it accepts (see my comment [here](https://github.com/marshallswain/feathers-pinia/issues/16#issuecomment-981096832)).

**Comment by marshallswain** [comment]
Released as `feathers-pinia@0.20.0`.  Thank you!

**Pull request merged**
